package myJava.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

class AutoGeneratedKeys {
	public static void main(String... args) throws Exception {
		PreparedStatement pstmt = null;
		ResultSet rs = null;
		Class.forName("oracle.jdbc.driver.OracleDriver");
		Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "oracle");
		Statement stmt = con.createStatement();
		stmt.executeUpdate("create table Student(name varchar(30), class number(2), marks number(4))");
		String query = "insert into Student (name,class,marks) values (?,?,?)";
		pstmt = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
		pstmt.setString(1, "John");
		pstmt.setInt(2, 12);
		pstmt.setInt(3, 489);
		pstmt.executeUpdate();
		rs = pstmt.getGeneratedKeys();
		if (rs.next()) {
			System.out.println("Generated Student RollNo:" + rs.getString(1));
		}
	}
}